project_id = "jddeuhrocglnisujixdt"

[functions.create-student-account]
verify_jwt = false

[functions.reset-student-password]
verify_jwt = false

[functions.send-email-smoke-test]
verify_jwt = true

[functions.send-enrollment-received-email]
verify_jwt = false